os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - choco install -y wsl-ubuntu-1804
  - wsl
  - export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y ansible
  - wsl ansible -m setup --connection=local
