os: windows
language: bash
services: docker

script:
  - powershell -NoProfile -ExecutionPolicy Bypass -Command "Install-Module DockerMsftProvider -Force"
  - powershell -NoProfile -ExecutionPolicy Bypass -Command "Install-Package Docker -ProviderName DockerMsftProvider -Force
  - docker version
  - docker images
  - docker info
  - powershell -NoProfile -ExecutionPolicy Bypass -Command "& $Env:ProgramFiles\Docker\Docker\DockerCli.exe"
