os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - choco install -y wsl-ubuntu-1804
  - wsl apt-get update && wsl apt-get install ansible
  - wsl ansible -m setup --connection=local
