os: windows
language: bash
services: docker

script:
  #- docker run mcr.microsoft.com/windows/nanoserver:1803 ipconfig
  - Install-Module DockerMsftProvider -Force
  - Install-Package Docker -ProviderName DockerMsftProvider -Force
  - docker version
  - docker images
  - docker info
  - $Env:ProgramFiles\Docker\Docker\DockerCli.exe --version