os: windows
language: bash
services: docker

script:
  - powershell -Command Install-Module DockerMsftProvider -Force
  - powershell -Command Install-Package Docker -ProviderName DockerMsftProvider -Force
  - docker version
  - docker images
  - docker info
  - C:/Program Files/Docker/Docker/DockerCli.exe --version
