os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - choco install -y wsl-ubuntu-1804
  - wsl apt update && wsl apt install -y ansible
  - wsl ansible -m setup --connection=local
