os: windows
language: bash
services: docker

install:
  - powershell -ExecutionPolicy ByPass -File bootstrap.ps1

script:
  - wsl ansible localhost -m setup --connection=local --extra-vars "ansible_user=ansible ansible_password=ansible ansible_connection=winrm ansible_winrm_server_cert_validation=ignore"
