os: windows
language: bash
services: docker

install:
  - powershell -ExecutionPolicy ByPass -File boostrap.ps1

script:
  - wsl ansible localhost -m setup --connection=local --extra-vars "ansible_user=ansible ansible_password=ansible ansible_connection=winrm"
